name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up NPM cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install project dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up NPM cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install project dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: Synapse
          path: dist

  # test-browser:
  #   name: Test Browsers
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Set up NPM cache
  #       uses: actions/cache@v2
  #       with:
  #         path: ./node_modules
  #         key: npm-cache-${{ hashFiles('**/package-lock.json') }}

  #     - name: Install project dependencies
  #       run: npm install

  #     - name: Fetch artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: Synapse
  #         path: dist

  #     - name: Run tests
  #       run: npm run test:browser

  #     - name: Upload coverage to codecov
  #       uses: codecov/codecov-action@v1
  #       with:
  #         file: coverage/lcov.info

  # test-node:
  #   name: Test Node
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Set up NPM cache
  #       uses: actions/cache@v2
  #       with:
  #         path: ./node_modules
  #         key: npm-cache-${{ hashFiles('**/package-lock.json') }}

  #     - name: Install project dependencies
  #       run: npm install

  #     - name: Fetch artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: Synapse
  #         path: dist

  #     - name: Run tests
  #       run: npm run test:node

  #     - name: Upload coverage to codecov
  #       uses: codecov/codecov-action@v1
  #       with:
  #         file: coverage/lcov.info

  # test-saucelabs:
  #   name: Test SauceLabs
  #   runs-on: ubuntu-latest
  #   needs: build
  #   concurrency: saucelabs
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Set up NPM cache
  #       uses: actions/cache@v2
  #       with:
  #         path: ./node_modules
  #         key: npm-cache-${{ hashFiles('**/package-lock.json') }}

  #     - name: Install project dependencies
  #       run: npm install

  #     - name: Fetch artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: Synapse
  #         path: dist

  #     - name: Run tests
  #       run: npm run test:saucelabs
  #       env:
  #         SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  #         SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
