name: Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Run build script
        run: yarn build

      - name: Prepare
        run: |
          mkdir public
          cp -rf examples public
          cp -rf dist public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: public
